site_name: Q Documentation
theme:
  name: material
repo_url: https://github.com/myOmikron/Q
repo_name: myOmikron/Q
edit_uri: https://github.com/myOmikron/q-docs/edit/main/docs/
markdown_extensions:
  - admonition
nav:
  - Home: index.md
  - Deployment:
    - Advanced:
      - Deploy a multi-proxy system: deployment/advanced/multi_proxy.md
      - Cronjobs: deployment/advanced/cronjobs.md
  - Usage:
      - Variables: usage/variables.md
  - Developer Resources:
      - API:
          - REST API: developer/api/rest_api.md
      - Internal API:
          - Q-Web: developer/api/internal_q_web.md
          - Q-Proxy: developer/api/internal_q_proxy.md
      - Checks:
          - Writing own checks: developer/checks/writing_checks.md
