site_name: Q Documentation
theme:
  name: material
nav:
  - Home: index.md
  - Developer Resource:
      - API: developer/api.md  - Developer Resources:
      - API:
          - REST API: developer/api/rest_api.md
